enableGlobalCache: false

logFilters:
  - level: discard
    text: "skystedt.se@workspace:. must be built because it never has been before or the last one failed"
  - level: discard
    text: "skystedt.se@workspace:. must be rebuilt because its dependency tree changed"

nodeLinker: node-modules

plugins:
  - checksum: 9a4c17b34d5dfa956c87c0667bceb162f1626595c9ba74a5264dc0f5fa89b3887b9c7cee54b70fed301cad890b2e8cf78427156f10edf1661551429a6d25537d
    path: .yarn/plugins/@yarnpkg/plugin-helloworld.cjs
    spec: ../yarn-plugin-hello-world/bundles/@yarnpkg/plugin-helloworld.js
