logFilters:
  - code: YN0002 # MISSING_PEER_DEPENDENCY
    level: error
  - code: YN0059 # INVALID_RANGE_PEER_DEPENDENCY
    level: error
  - code: YN0060 # INCOMPATIBLE_PEER_DEPENDENCY
    level: error
