enableGlobalCache: false

logFilters:
  - level: discard
    text: "skystedt.se@workspace:. must be built because it never has been before or the last one failed"
  - level: discard
    text: "skystedt.se@workspace:. must be rebuilt because its dependency tree changed"

nodeLinker: node-modules

plugins:
  - checksum: e30af02673c0c031794e48266825e8a98e423f62f3b7d0b096f5acd3106aa13d2968d02c5a559ccd8619ef786051abf4f7ed45d22211028a9cb9f04abbc50e12
    path: .yarn/plugins/@yarnpkg/plugin-helloworld.cjs
    spec: ../yarn-plugin-hello-world/bundles/@yarnpkg/plugin-helloworld.js
