enableGlobalCache: false

logFilters:
  - level: discard
    text: "skystedt.se@workspace:. must be built because it never has been before or the last one failed"
  - level: discard
    text: "skystedt.se@workspace:. must be rebuilt because its dependency tree changed"

nodeLinker: node-modules

plugins:
  - checksum: 69fbafbbf610e15268536a27f152976e40bc7f2ef780044ac1a870f1ae775acc8cef5dcd5bf0caec52e11d5f524ca66f218881925d22e325e8d417be80b63f37
    path: .yarn/plugins/@yarnpkg/plugin-peer-patch.cjs
    spec: ../Plugins/yarn-plugin-peer-patch/bundles/@yarnpkg/plugin-peer-patch.js
  - checksum: e5e6e2885ab0e6521b70b0af7c6d8ca2c75dcae2403706fc4600a783b339a6530a476dafb9450c9436ca4050eb6bdee9b62e6e2cebfecf1e81dd709a2480dc07
    path: .yarn/plugins/@yarnpkg/plugin-engines.cjs
    spec: "https://raw.githubusercontent.com/devoto13/yarn-plugin-engines/e6556920ba18593fb775bfcdf12fbc2af50b2642/bundles/%40yarnpkg/plugin-engines.js"
