nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.6.1.cjs

packageExtensions:
  '@microsoft/dynamicproto-js@*':
    peerDependencies:
      typescript: '*'
  '@microsoft/applicationinsights-analytics-js@*':
    peerDependencies:
      typescript: '*'
  '@microsoft/applicationinsights-channel-js@*':
    peerDependencies:
      typescript: '*'
  '@microsoft/applicationinsights-common@*':
    peerDependencies:
      typescript: '*'
  '@microsoft/applicationinsights-core-js@*':
    peerDependencies:
      typescript: '*'
  '@microsoft/applicationinsights-dependencies-js@*':
    peerDependencies:
      typescript: '*'
  '@microsoft/applicationinsights-properties-js@*':
    peerDependencies:
      typescript: '*'
  '@microsoft/applicationinsights-shims@*':
    peerDependencies:
      typescript: '*'
  '@microsoft/applicationinsights-web@*':
    peerDependencies:
      typescript: '*'
