name: Reusable - Azure Static Web Apps - Build

on:
  workflow_call:

jobs:
  build_and_deploy:
    name: Azure Static Web Apps - Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.2.0
      - id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/src/client"
          api_location: "/src/api"
          output_location: "dist"
          app_build_command: "npm run production"
