name: Build - Reusable

on:
  workflow_call:

env:
  WORKING_DIR: "src"
  OUTPUT_DIR: "publish"
  API_DIR: "Api"
  CLIENT_DIR: "Client"
  DOTNET_CONFIGURATION: "Release"
  
jobs:
  build_test_and_deploy:
    name: Azure Static Web Apps - Build/Test/Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIR }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
  
      - name: .NET Setup
        uses: actions/setup-dotnet@v3
        with:
          global-json-file: ${{ env.WORKING_DIR }}/global.json
          
      - name: .NET Restore
        run: dotnet restore
      
      - name: .NET Build
        run: dotnet build --configuration ${{ env.DOTNET_CONFIGURATION }} --no-restore
    
      - name: .NET Test
        run: dotnet test --configuration ${{ env.DOTNET_CONFIGURATION }} --no-build

      - name: .NET Publish
        run: dotnet publish ${{ env.API_DIR }} --output ${{ env.OUTPUT_DIR }}/${{ env.API_DIR }} --configuration ${{ env.DOTNET_CONFIGURATION }} --no-build

      - name: Node Setup
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'
          
      - name: Corepack Enable
        run: corepack enable

      - name: Yarn Install
        run: yarn install --immutable
        working-directory: ${{ env.WORKING_DIR }}/${{ env.CLIENT_DIR }}
        
      - name: Yarn Build
        run: yarn run production
        working-directory: ${{ env.WORKING_DIR }}/${{ env.CLIENT_DIR }}

      - name: Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          config_file_location: ${{ env.WORKING_DIR }}/${{ env.OUTPUT_DIR }}
          app_location: ${{ env.WORKING_DIR }}/${{ env.OUTPUT_DIR }}/${{ env.CLIENT_DIR }}
          api_location: ${{ env.WORKING_DIR }}/${{ env.OUTPUT_DIR }}/${{ env.API_DIR }}
          skip_app_build: true
          skip_api_build: true
