name: Dependabot

concurrency: 
  group: aswa-${{ github.ref }}
  cancel-in-progress: false

on:
  push:
    branches:
      - main
  pull_request_target:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  build_and_deploy:
    name: Build
    if: github.actor == 'dependabot[bot]'
    uses: ./.github/workflows/azure-static-web-apps-build-and-deploy.yml
    secrets: inherit
