name: Push main

concurrency:
  group: push-main-${{ github.ref }}
  cancel-in-progress: false

on:
  push:
    branches:
      - main

permissions:
  actions: read
  contents: read
  pull-requests: write

jobs:
  build_test_and_deploy:
    name: Build, Test and Deploy
    uses: ./.github/workflows/reusable-build-test-deploy.yml
    secrets: inherit
