name: Reusable - Build, Test and Deploy

on:
  workflow_call:

# permissions are inherited from the caller

env:
  SRC_DIR: "src"
  PUBLISH_DIR: "publish"
  API_DIR: "Api"
  CLIENT_DIR: "Client"
  DOTNET_CONFIGURATION: "Release"
  SWA_NAME: "skystedt"
  SCRIPTS_DIR: "${{ github.workspace }}/.github/scripts"
  DEPLOY_DIR: "${{ github.workspace }}/.github/deploy"

jobs:
  build_api:
    name: Build API
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.SRC_DIR }}
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # 7.0.0

      - name: Dotnet Setup
        uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # 6.0.0
        with:
          global-json-file: ${{ env.SRC_DIR }}/global.json

      - name: Dotnet Restore
        run: dotnet restore

      - name: Dotnet Build
        run: dotnet build --configuration ${{ env.DOTNET_CONFIGURATION }} --no-incremental --no-restore

      - name: Dotnet Test
        run: dotnet test --configuration ${{ env.DOTNET_CONFIGURATION }} --no-build

      - name: Dotnet Publish
        run: dotnet publish ${{ env.API_DIR }} --output ${{ env.PUBLISH_DIR }}/${{ env.API_DIR }} --configuration ${{ env.DOTNET_CONFIGURATION }} --no-build

      - name: Upload Artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # 7.0.1
        with:
          name: api
          include-hidden-files: true
          path: ${{ env.SRC_DIR }}/${{ env.PUBLISH_DIR }}/${{ env.API_DIR }}

  build_client:
    name: Build Client
    runs-on: ubuntu-latest
    env:
      YARN_ENABLE_HARDENED_MODE: 1
    defaults:
      run:
        working-directory: ${{ env.SRC_DIR }}
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # 7.0.0

      - name: Node Setup
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # 7.0.0
        with:
          node-version-file: ${{ env.SRC_DIR }}/${{ env.CLIENT_DIR }}/package.json
          check-latest: true
          
      - name: Corepack Setup
        run: npm install -g corepack

      - name: Corepack Enable
        run: corepack enable

      - name: Dotnet Setup
        uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # 6.0.0
        with:
          global-json-file: ${{ env.SRC_DIR }}/global.json

      - name: Merge Yarn Settings
        run: dotnet run ${{ env.SCRIPTS_DIR }}/MergeYarnSettings.cs -- ${{ env.CLIENT_DIR }}/.yarnrc.production.yml

      - name: Yarn Install
        run: yarn install --immutable
        working-directory: ${{ env.SRC_DIR }}/${{ env.CLIENT_DIR }}

      - name: Yarn Typecheck
        run: yarn run typecheck
        working-directory: ${{ env.SRC_DIR }}/${{ env.CLIENT_DIR }}

      - name: Yarn Build
        run: yarn run production
        working-directory: ${{ env.SRC_DIR }}/${{ env.CLIENT_DIR }}

      - name: Upload Config
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # 7.0.1
        with:
          path: ${{ env.SRC_DIR }}/${{ env.PUBLISH_DIR }}/staticwebapp.config.json
          archive: false

      - name: Upload Artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # 7.0.1
        with:
          name: client
          path: ${{ env.SRC_DIR }}/${{ env.PUBLISH_DIR }}/${{ env.CLIENT_DIR }}

  deploy:
    name: Deploy
    needs: [build_api, build_client]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # 7.0.0

      - name: Download Config
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # 8.0.1
        with:
          name: staticwebapp.config.json
          path: ${{ github.workspace }}/artifacts/config

      - name: Download Api
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # 8.0.1
        with:
          name: api
          path: ${{ github.workspace }}/artifacts/api

      - name: Download Client
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # 8.0.1
        with:
          name: client
          path: ${{ github.workspace }}/artifacts/client

      - name: Install Azure Static Web Apps CLI
        run: |
          SWA_CLI_VERSION=$(jq --raw-output '.dependencies["@azure/static-web-apps-cli"]' ${{ env.DEPLOY_DIR }}/package.json)
          npm install -g "@azure/static-web-apps-cli@$SWA_CLI_VERSION"

      - name: Azure Login
        uses: azure/login@532459ea530d8321f2fb9bb10d1e0bcf23869a43 # 3.0.0
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Get Deployment Token
        run: |
          SWA_CLI_DEPLOYMENT_TOKEN=$(az staticwebapp secrets list --name ${{ env.SWA_NAME }} --query "properties.apiKey" --output tsv)
          echo "::add-mask::$SWA_CLI_DEPLOYMENT_TOKEN"
          echo "SWA_CLI_DEPLOYMENT_TOKEN=$SWA_CLI_DEPLOYMENT_TOKEN" >> "$GITHUB_ENV"

      - name: Azure Static Web Apps - Deploy
        run: |
          API_RUNTIME=$(jq --raw-output '.platform.apiRuntime' ${{ github.workspace }}/artifacts/config/staticwebapp.config.json)
          API_LANGUAGE="${API_RUNTIME%:*}"
          API_LANGUAGE="${API_LANGUAGE//-/}"
          API_VERSION="${API_RUNTIME#*:}"
          DEPLOYMENT_ENVIRONMENT="${{ github.event_name == 'pull_request' && github.event.number || 'production' }}"

          swa deploy \
            ${{ github.workspace }}/artifacts/client \
            --api-location ${{ github.workspace }}/artifacts/api \
            --swa-config-location ${{ github.workspace }}/artifacts/config \
            --api-language "$API_LANGUAGE" \
            --api-version "$API_VERSION" \
            --env "$DEPLOYMENT_ENVIRONMENT"

      - name: Get Preview Environment Url
        if: github.event_name == 'pull_request'
        run: |
          ENVIRONMENT_HOSTNAME=$(az staticwebapp environment show --name ${{ env.SWA_NAME }} --environment-name ${{ github.event.number }} --query "hostname" --output tsv)
          echo "Azure Static Web Apps: https://$ENVIRONMENT_HOSTNAME" > "$RUNNER_TEMP/deployment-url.md"

      - name: Find Url Comment
        id: url_comment
        if: github.event_name == 'pull_request'
        uses: ./.github/composite/marker-comment-find
        with:
          issue: ${{ github.event.number }}
          marker: deployment-url-comment

      - name: Comment Url On Pull Request
        if: github.event_name == 'pull_request'
        uses: ./.github/composite/marker-comment-write
        with:
          issue: ${{ github.event.number }}
          comment-id: ${{ steps.url_comment.outputs.id }}
          markers: deployment-url-comment
          body-file: ${{ runner.temp }}/deployment-url.md

      - name: Azure Logout
        if: always()
        run: az logout
