name: Schedule - Scan OWASP Dependency Check

on:
  schedule:
    # Run daily at 11:45 UTC: owasp/dependency-check-action:latest is rebuilt daily at 11:30 UTC
    - cron: "45 11 * * *"
  workflow_dispatch:

permissions: {} # permissions are specified on each job

jobs:
  scan:
    name: Scan OWASP Dependency Check
    permissions:
      contents: write
      security-events: write
      pull-requests: write
    uses: ./.github/workflows/reusable-scan-owasp-dependency-check.yml
    with:
      upload-sarif: true
      report-pull-request: true
