name: Schedule - Cleanup PR Environments

on:
  schedule:
    # Run every Saturday at 03:40 UTC (04:40 CET/05:40 CEST), some time before Dependabot is scheduled to run
    - cron: "40 3 * * 6"
  workflow_dispatch:

permissions: {} # permissions are specified on each job

env:
  SWA_NAME: "skystedt"

jobs:
  find_orphaned:
    name: Find Orphaned Environments
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      pull-requests: read

    outputs:
      orphaned: ${{ steps.orphaned.outputs.orphaned }}

    steps:
      - name: Azure Login
        uses: azure/login@532459ea530d8321f2fb9bb10d1e0bcf23869a43 # 3.0.0
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Get Azure SWA Preview Environments
        run: |
          ENVIRONMENTS=$(az staticwebapp environment list --name ${{ env.SWA_NAME }} --query "[].name" | jq -r -c '[.[] | select(test("^[0-9]+$")) | tonumber]')
          echo "ENVIRONMENTS=$ENVIRONMENTS" >> "$GITHUB_ENV"
          echo "Found environments: $ENVIRONMENTS"

      - name: Get Open PRs
        if: env.ENVIRONMENTS != '[]'
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
        run: |
          OPEN_PRS=$(gh pr list --state open --json number | jq -r -c '[.[].number]')
          echo "OPEN_PRS=$OPEN_PRS" >> "$GITHUB_ENV"
          echo "Found open PRs: $OPEN_PRS"

      - name: Determine Orphaned Environments
        id: orphaned
        run: |
          ORPHANED=$(jq -n -c --argjson environments "${ENVIRONMENTS:-[]}" --argjson open_prs "${OPEN_PRS:-[]}" '$environments - $open_prs')
          echo "orphaned=$ORPHANED" >> "$GITHUB_OUTPUT"
          echo "Orphaned environments: $ORPHANED"

      - name: Azure Logout
        if: always()
        run: az logout

  cleanup:
    name: Cleanup
    needs: find_orphaned
    if: needs.find_orphaned.outputs.orphaned != '[]'

    permissions:
      id-token: write

    strategy:
      fail-fast: false
      matrix:
        pr_number: ${{ fromJson(needs.find_orphaned.outputs.orphaned) }}
    uses: ./.github/workflows/reusable-cleanup.yml
    with:
      pr_number: ${{ matrix.pr_number }}
    secrets: inherit
