name: Schedule - Cleanup PR Environments

on:
  schedule:
    # Run every Saturday at 03:40 UTC (04:40 CET/05:40 CEST), some time before Dependabot is scheduled to run
    - cron: "40 3 * * 6"
  workflow_dispatch:

permissions:
  id-token: write
  actions: write
  
env:
  SWA_NAME: "skystedt"

jobs:
  cleanup:
    name: Cleanup PR Environments
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # 7.0.0

      - name: Azure Login
        uses: azure/login@532459ea530d8321f2fb9bb10d1e0bcf23869a43 # 3.0.0
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Get Azure SWA Preview Environments
        run: |
          ENVIRONMENTS=$(az staticwebapp environment list --name ${{ env.SWA_NAME }} --query "[?pullRequestTitle!=null].name" | jq -r -c '[.[] | tonumber]')
          echo "ENVIRONMENTS=$ENVIRONMENTS" >> "$GITHUB_ENV"
          echo "Found environments: $ENVIRONMENTS"

      - name: Get Open PRs
        if: env.ENVIRONMENTS != '[]'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          OPEN_PRS=$(gh pr list --state open --json number | jq -r -c '[.[].number]')
          echo "OPEN_PRS=$OPEN_PRS" >> "$GITHUB_ENV"
          echo "Found open PRs: $OPEN_PRS"

      - name: Cleanup Orphaned Environments
        if: env.ENVIRONMENTS != '[]'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "$ENVIRONMENTS" | jq -r '.[]' | while IFS= read -r PR_NUMBER; do
            if echo "$OPEN_PRS" | grep -Fw "$PR_NUMBER"; then
              echo "PR #$PR_NUMBER is open, skip cleanup"
            else
              echo "Cleaning up PR #$PR_NUMBER"
              gh workflow run reusable-cleanup.yml -f pr_number=$PR_NUMBER
            fi
          done

      - name: Azure Logout
        if: always()
        run: az logout
